### ISSUE TITLE
Mega Spectral Pack crash

### ISSUE THREAD

**Issue by jamesneal** [MathIsFun0/Cryptid#28] opened 2024-07-13 05:56 UTC
I get this crash pretty regularly while mousing over the Spectral card offerings in a Mega Spectral Pack (Antimatter Deck). In this instance, I had just moved my pointer from Wraith to Cryptid. 

<img width="1200" alt="Screenshot" src="https://github.com/user-attachments/assets/b7d68139-d277-48a7-95bb-ddb3abd35ad4">

```
Oops! The game crashed:
functions/misc_functions.lua:1862: attempt to index field 'vars' (a nil value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0712a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.4.1b]
    2: More Speed by Steamo [ID: MoreSpeed]
    3: Talisman by MathIsFun_ [ID: Talisman, Version: 1.2.2]

Stack Traceback
===============
(3) Lua global 'localize' at file 'functions/misc_functions.lua:1862'
Local variables:
 args = table: 0x032fab4db0  {type:other, key:s_cry_azure_seal, nodes:table: 0x032fab4d20}
 misc_cat = nil
<img width="1200" alt="Screenshot 2024-07-12 at 10 46 02 PM" src="https://github.com/user-attachments/assets/148a161d-70b3-4fd9-9484-834ffa08cbce">

 loc_target = table: 0x03046459a8  {name_parsed:table: 0x012cd38bb8, text:table: 0x0304645a28, name:Azure Seal (more...)}
 ret_string = nil
 (for generator) = C function: builtin#6
 (for state) = table: 0x012a7e3e60  {1:table: 0x012a7e3f10, 2:table: 0x0128af7ee8, 3:table: 0x012cd6d678, 4:table: 0x012cd50af8 (more...)}
 (for control) = number: 1
 _ = number: 1
 lines = table: 0x012a7e3f10  {1:table: 0x012a7e4008, 2:table: 0x012a421468, 3:table: 0x012a4144c8, 4:table: 0x012a414610 (more...)}
 final_line = table: 0x032fab4e60  {1:table: 0x032fab4ea8}
 (for generator) = C function: builtin#6
 (for state) = table: 0x012a7e3f10  {1:table: 0x012a7e4008, 2:table: 0x012a421468, 3:table: 0x012a4144c8, 4:table: 0x012a414610 (more...)}
 (for control) = number: 2
 _ = number: 2
 part = table: 0x012a421468  {strings:table: 0x012a421358, control:table: 0x012a4213a0}
 assembled_string = string: ""
 (for generator) = C function: builtin#6
 (for state) = table: 0x012a421358  {1:table: 0x012a4213e8}
 (for control) = number: 1
 _ = number: 1
 subpart = table: 0x012a4213e8  {1:1}
 (*temporary) = string: ""
 (*temporary) = nil
 (*temporary) = number: 1
 (*temporary) = number: 2.45843e-314
 (*temporary) = number: 1
 (*temporary) = number: 4
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = table: 0x012ce60f20  {1:Diamonds, 2:Clubs, 3:Hearts, 4:Spades}
 (*temporary) = number: 4
 (*temporary) = table: 0x0128c91288  {1:0.23529411764706, 2:0.26274509803922, 3:0.4078431372549, 4:1}
 (*temporary) = string: "Spades"
 (*temporary) = string: "attempt to index field 'vars' (a nil value)"
(4) Lua global 'generate_card_ui' at file 'functions/common_events.lua:2698'
Local variables:
 _c = table: 0x03322f96d0  {set:Other, key:s_cry_azure_seal, specific_vars:table: 0x03307d2460}
 full_UI_table = table: 0x033078c878  {info:table: 0x03317065a8, main:table: 0x033078c928, badges:table: 0x033078c830 (more...)}
 specific_vars = nil
 card_type = nil
 badges = nil
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = nil
 first_pass = nil
 desc_nodes = table: 0x032fab4d20  {}
 name_override = nil
 info_queue = table: 0x032fab4cd8  {}
 loc_vars = table: 0x032fab4d68  {}
(5) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:3030'
Local variables:
 _c = table: 0x0304645c88  {config:table: 0x0304645e58, object_type:Consumable, registered:true, _d:false (more...)}
 full_UI_table = table: 0x033078c878  {info:table: 0x03317065a8, main:table: 0x033078c928, badges:table: 0x033078c830 (more...)}
 specific_vars = nil
 card_type = string: "Undiscovered"
 badges = table: 0x033078c830  {}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x0129304f40  {tilt_var:table: 0x0330b126e0, config:table: 0x0330b12618, sprite_facing:front (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x033078c928  {1:table: 0x03307d2568, 2:table: 0x0330c4d5a8, 3:table: 0x0330fc1d98}
 name_override = nil
 info_queue = table: 0x0331706638  {1:table: 0x03322f96d0}
 loc_vars = table: 0x03322f94e8  {}
 (for generator) = C function: builtin#6
 (for state) = table: 0x0331706638  {1:table: 0x03322f96d0}
 (for control) = number: 1
 _ = number: 1
 v = table: 0x03322f96d0  {set:Other, key:s_cry_azure_seal, specific_vars:table: 0x03307d2460}
(6) Lua method 'hover' at file 'card.lua:4627'
Local variables:
 self = table: 0x0129304f40  {tilt_var:table: 0x0330b126e0, config:table: 0x0330b12618, sprite_facing:front (more...)}
(7) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x0128ad4d00  {cursor_hover:table: 0x0128ad51c0, HID:table: 0x0128b5e4c8, cursor_position:table: 0x0128ad4f20 (more...)}
 dt = number: 0.0083455
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2673'
Local variables:
 self = table: 0x01289f4fb0  {HUD:table: 0x0330dd66c8, WINDOWTRANS:table: 0x03301db718, CANV_SCALE:1 (more...)}
 dt = number: 0.0083455
(9) Lua upvalue 'upd' at file 'main.lua:487'
Local variables:
 self = table: 0x01289f4fb0  {HUD:table: 0x0330dd66c8, WINDOWTRANS:table: 0x03301db718, CANV_SCALE:1 (more...)}
 dt = number: 0.0083455
(10) Lua upvalue 'upd' at file 'main.lua:7820'
Local variables:
 self = table: 0x01289f4fb0  {HUD:table: 0x0330dd66c8, WINDOWTRANS:table: 0x03301db718, CANV_SCALE:1 (more...)}
 dt = number: 0.0083455
(11) Lua upvalue 'upd' at line 684 of chunk '"Mods/Cryptid/Items/Blinds.lua"]'
Local variables:
 self = table: 0x01289f4fb0  {HUD:table: 0x0330dd66c8, WINDOWTRANS:table: 0x03301db718, CANV_SCALE:1 (more...)}
 dt = number: 0.0083455
(12) Lua method 'update' at line 1918 of chunk '"Mods/Cryptid/Items/MiscJokers.lua"]'
Local variables:
 self = table: 0x01289f4fb0  {HUD:table: 0x0330dd66c8, WINDOWTRANS:table: 0x03301db718, CANV_SCALE:1 (more...)}
 dt = number: 0.0083455
(13) Lua field 'update' at file 'main.lua:137'
Local variables:
 dt = number: 0.0083455
(14) Lua function '?' at file 'main.lua:81' (best guess)
(15) global C function 'xpcall'
(16) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 52 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
```

**Comment by jamesneal** [comment] 2024-07-13 06:16
I'm wrong:
It was the mouse-over to Typhoon that did it.  Mousing over Typhoon consistently gives me this crash, even in Collection.

**Comment by MathIsFun0** [comment] 2024-07-14 16:44
Try updating Steamodded, as I'm unable to reproduce your issue on the latest version of it.

**Comment by warnerrrrr** [comment] 2024-07-17 22:46
> Try updating Steamodded, as I'm unable to reproduce your issue on the latest version of it.
but i need to have the alpha, no? or does this just not work on mac at all? when i try and start a new run the game crashes every time

**Comment by MathIsFun0** [comment] 2024-07-20 17:18
yeah, you need the alpha; going to close this issue as it doesn't happen on the latest version of Steamodded due to some recent API changes made along with the new seal being added

**Closed by MathIsFun0** 2024-07-20 17:18 UTC

**Comment by jamesneal** [comment] 2024-07-20 17:21
Just confirming that this crash is fixed for me. Thanks!
